apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshangularappdeploymentv2
spec:
  replicas: 6
  selector:
    matchLabels:
      app: freshangularapp
  template:
    metadata:
      labels:
        app: freshangularapp
    spec:
      containers:
      - name: aipfreshregistry
        image: aipfreshregistry.azurecr.io/freshangularapprepo:v2.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: freshangularappservicev2
spec:
  selector:
    app: freshangularapp
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  #type: NodePort
